apiVersion: v2
name: dima-traffic-gen
version: 1.0.0
description: Traffic generator for dima
type: application
keywords:
  - dima
home: https://github.com/feature-creeps/observability-workshop
sources:
  - https://github.com/feature-creeps/observability-workshop