apiVersion: v2
name: dima-frontend
version: 1.0.0
description: Frontend for dima
type: application
keywords:
  - dima
home: https://github.com/feature-creeps/observability-workshop
sources:
  - https://github.com/feature-creeps/observability-workshop