---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: frontend
        image: dima-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "500m"
