apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: olly-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend-service
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix
          - backend:
              service:
                name: imageholder-service
                port:
                  number: 8080
            path: /proxy/imageholder-service/(.*)
            pathType: Prefix