---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: imageholder
  template:
    metadata:
      labels:
        app: imageholder
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: imageholder
        image: dima-imageholder
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "json-log"
        - name: EVENTS_ENABLED
          value: "true"
        - name: BUSINESS_METRICS_ENABLED
          value: "true"
        - name: TRACING_TAGS_ENABLED
          value: "true"
        - name: APM_ENABLED
          value: "true"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
