apiVersion: v2
name: dima-imagethumbnail
version: 1.0.0
description: Microservice imagethumbnail for dima
type: application
keywords:
  - dima
home: https://github.com/feature-creeps/observability-workshop
sources:
  - https://github.com/feature-creeps/observability-workshop