---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: olly-dima
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}