---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: imagegrayscale
  template:
    metadata:
      labels:
        app: imagegrayscale
    spec:
      containers:
      - name: imagegrayscale
        image: dima-imagegrayscale
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
