apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-gen
spec:
  template:
    spec:
      containers:
      - name: traffic-gen
        image: gcr.io/olly-2021-k8s-migration/dima-traffic-gen:e7586ae5183498169f8147892653162935f9e379
        imagePullPolicy: IfNotPresent
        env:
        - name: IMAGEHOLDER_BASEURL
          value: "https://o11y.fans/proxy/imageholder"
        - name: IMAGEORCHESTRATOR_BASEURL
          value: "https://o11y.fans/proxy/imageorchestrator"
      restartPolicy: OnFailure
  backoffLimit: 4
