apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: jaeger-ingress
  namespace: istio-system
spec:
  rules:
    - host: "jaeger.o11y.tk"
      http:
        paths:
          - backend:
              service:
                name: jaeger
                port:
                  number: 80
            path: /(.*)
            pathType: Prefix