apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-level-9.yml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - --wiredTigerCacheSizeGB
        - "2"
        image: mongo:3.2.12
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: olly-mongodb
      restartPolicy: Always
      volumes:
      - name: olly-mongodb
        persistentVolumeClaim:
          claimName: olly-mongodb
status: {}
