version: '3'
services:

  ## Domain

  imageorchestrator:
    build: ../../../../imageorchestrator
    environment:
      JAVA_DEBUG: "true"
    ports:
      - 8080:8080
      - 5005:5005

  imageholder:
    build: ../../../../imageholder
    depends_on:
      - mongodb-service
    ports:
      - 8080

  imagerotator:
    build: ../../../../imagerotator
    ports:
      - 8080

  imagegrayscale:
    build: ../../../../imagegrayscale
    ports:
      - 8080

  ## Storage

  # database
  mongodb-service:
    image: mongo:3.2.12
    ports:
      - '27017'