apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-index
spec:
  template:
    spec:
      containers:
        - name: kibana-index
          image: gcr.io/olly-2021-k8s-migration/kibana-index:latest
          imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 4
