---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: traffic-gen
  template:
    metadata:
      labels:
        app: traffic-gen
    spec:
      containers:
      - name: traffic-gen
        image: traffic-gen
        env:
        - name: IMAGEHOLDER_BASEURL
          value: http://imageholder-service:8080
        - name: IMAGEORCHESTRATOR_BASEURL
          value: http://imageorchestrator-service:8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
