---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: olly-dima
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}