---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: imagethumbnail
  template:
    metadata:
      labels:
        app: imagethumbnail
    spec:
      containers:
      - name: imagethumbnail
        image: dima-imagethumbnail
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
