---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: imageflip
  template:
    metadata:
      labels:
        app: imageflip
    spec:
      containers:
      - name: imageflip
        image: dima-imageflip
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: json-log
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
