version: '3.7'
services:

  ## Domain
  frontend-service:
    image: ${GKE_REGISTRY}/dima-frontend:${GITHUB_SHA}

  imageorchestrator-service:
    image: ${GKE_REGISTRY}/dima-imageorchestrator:${GITHUB_SHA}

  imageholder-service:
    image: ${GKE_REGISTRY}/dima-imageholder:${GITHUB_SHA}

  imagerotator-service:
    image: ${GKE_REGISTRY}/dima-imagerotator:${GITHUB_SHA}

  imagegrayscale-service:
    image: ${GKE_REGISTRY}/dima-imagegrayscale:${GITHUB_SHA}

  imageresize-service:
    image: ${GKE_REGISTRY}/dima-imageresize:${GITHUB_SHA}

  imageflip-service:
    image: ${GKE_REGISTRY}/dima-imageflip:${GITHUB_SHA}

  imagethumbnail-service:
    image: ${GKE_REGISTRY}/dima-imagethumbnail:${GITHUB_SHA}

  traffic-gen:
    image: ${GKE_REGISTRY}/dima-traffic-gen:${GITHUB_SHA}