version: '3.7'
services:

  ## Domain
  frontend-service:
    build: ../application/frontend
    depends_on:
      - fluentd
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageorchestrator-service:
    build: ../application/imageorchestrator
    depends_on:
    - fluentd
    ports:
    - 8080:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageholder-service:
    build: ../application/imageholder
    depends_on:
    - mongodb
    - fluentd
    ports:
    - 8081:8080
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagerotator-service:
    build: ../application/imagerotator
    depends_on:
      - fluentd
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagegrayscale-service:
    build: ../application/imagegrayscale
    depends_on:
      - fluentd
    ports:
      - 8083:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageresize-service:
    build: ../application/imageresize
    depends_on:
      - fluentd
    ports:
      - 8084:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageflip-service:
    build: ../application/imageflip
    depends_on:
      - fluentd
    ports:
      - 8085:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagethumbnail-service:
    build: ../application/imagethumbnail
    depends_on:
      - fluentd
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 4g
    env_file:
      - .env
      - level_env_vars/base.env
      - level_env_vars/override_2.env
      - level_env_vars/override_3.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  traffic-gen:
    build: ../infrastructure/traffic-gen
    depends_on:
    - fluentd
    - imageholder
    - imageorchestrator
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12

    # See https://github.com/docker-library/docs/tree/master/mongo#setting-wiredtiger-cache-size-limits
    command: "--wiredTigerCacheSizeGB 2"
    depends_on:
    - fluentd
    ports:
    - '27017'
    volumes:
    - olly-mongodb:/data/db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  ## Logging

  # log collector
  fluentd:
    build: ../infrastructure/fluentd
    command: -qq
    depends_on:
    - elasticsearch
    volumes:
    - /var/lib/docker/containers/:/mnt/var/log/docker/containers/:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - "24224:24224"
    - "24224:24224/udp"

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    env_file:
      - .elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - olly-elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana-index:
    build: ../infrastructure/kibana-index
    depends_on:
    - kibana
    - elasticsearch
    restart: on-failure

  # logs visualizer
  kibana:
    build: ../infrastructure/kibana
    depends_on:
    - elasticsearch
    volumes:
    - olly-prometheus:/prometheus
    ports:
    - 5601:5601

  heartbeat:
    build: ../infrastructure/heartbeat
    user: root
    # disable strict permission checks
    command: ["--strict.perms=false"]
    depends_on:
      - kibana
      - elasticsearch

volumes:
  olly-elasticsearch:
    driver: local
  olly-mongodb:
    driver: local
  olly-prometheus:
    driver: local
  olly-metricbeat:
    driver: local
