version: '3.7'
services:

  ## Domain
  frontend-service:
    build: ../application/frontend
    ports:
      - 80:80

  imageorchestrator-service:
    build: ../application/imageorchestrator
    ports:
    - 8080:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imageholder-service:
    build: ../application/imageholder
    depends_on:
    - mongodb
    ports:
    - 8081:8080
    deploy:
      resources:
        limits:
          memory: 1g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imagerotator-service:
    build: ../application/imagerotator
    ports:
      - 8082:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imagegrayscale-service:
    build: ../application/imagegrayscale
    ports:
      - 8083:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imageresize-service:
    build: ../application/imageresize
    ports:
      - 8084:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imageflip-service:
    build: ../application/imageflip
    ports:
      - 8085:8080
    deploy:
      resources:
        limits:
          memory: 2g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  imagethumbnail-service:
    build: ../application/imagethumbnail
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 4g
    env_file:
      - .env
      - level_env_vars/base.env
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}

  traffic-gen:
    build: ../infrastructure/traffic-gen
    depends_on:
    - imageholder
    - imageorchestrator
    restart: on-failure

  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12

    # See https://github.com/docker-library/docs/tree/master/mongo#setting-wiredtiger-cache-size-limits
    command: "--wiredTigerCacheSizeGB 2"
    ports:
    - '27017'
    volumes:
    - olly-mongodb:/data/db

  ## Logging

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    env_file:
      - .elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - olly-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana-index:
    build: ../infrastructure/kibana-index
    depends_on:
      - kibana
      - elasticsearch
    restart: on-failure

  # logs visualizer
  kibana:
    build: ../infrastructure/kibana
    depends_on:
      - elasticsearch
    volumes:
      - olly-prometheus:/prometheus
    ports:
      - 5601:5601

volumes:
  olly-elasticsearch:
    driver: local
  olly-mongodb:
    driver: local
  olly-prometheus:
    driver: local
  olly-metricbeat:
    driver: local
