resources:
  - "./../base"
  - ingress.yaml
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
namePrefix: frontend-

images:
  - name: dima-frontend
    newName: gcr.io/olly-2021-k8s-migration/dima-frontend
    newTag: 32ef28fee149f1e8e130d9c655b3892078302dae