---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: imagegrayscale
  template:
    metadata:
      labels:
        app: imagegrayscale
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: imagegrayscale
        image: dima-imagegrayscale
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: json-log
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "800Mi"
            cpu: "1000m"
