---
apiVersion: v1
kind: Service
metadata:
  labels:
    group: olly-infrastructure
  name: {{ template "dima-mongodb.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}