---
replicas: 1
resources:
  requests:
    cpu: "500m"
    memory: "1500Mi"
  limits:
    cpu: "500m"
    memory: "1500Mi"
secret:
  enabled: true
  password: "changeme"
replicas: 1
volumeClaimTemplate:
  resources:
    requests:
      storage: 10Gi