name: Build and call deploy subsequently
on:
  workflow_dispatch:
  inputs:
      service:
        description: 'Image tag'
        required: false
        default: 'latest'
      tag:
        description: 'Image tag'
        required: false
        default: 'latest'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Building service ${{ github.event.inputs.service }}:${{ github.event.inputs.tag }}!"

  call_deployment:
    uses: feature-creeps/observability-workshop/.github/workflows/deploy.yml@k8s
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets:
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}