name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
      tag:
        description: 'Image tag'
        required: false
        default: 'latest'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
          echo "deploying ${{ github.event.inputs.tag }}!"

  call_deployment:
    uses: feature-creeps/observability-workshop/.github/workflows/deploy.yml@k8s
    with:
      tag: ${{ github.event.inputs.tag }}