name: Build

on: push

env:
  GKE_REGISTRY: gcr.io/${{ secrets.GKE_PROJECT }}

jobs:
  setup-build-publish:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.GKE_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Install docker-compose for python3
        run: pip3 install docker-compose --upgrade

      - name: Build all images
        working-directory: ./stack/compose
        run: docker-compose -f docker-compose.yml -f docker-compose-registry-tags.yml build --parallel

      - name: Push all images
        working-directory: ./stack/compose
        run: docker-compose -f docker-compose.yml -f docker-compose-registry-tags.yml push
